name: PR Review Agent

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  pr-review-agent:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Claude Code CLI
        run: |
          # Simulate Claude Code installation for demo
          echo "Installing Claude Code CLI..."
          echo "✅ Claude Code CLI installed"

      - name: Run PR Review Agent
        run: |
          echo "🤖 Triggering pr-reviewer-gitops agent..."
          echo ""
          echo "PR Details:"
          echo "Title: ${{ github.event.pull_request.title }}"
          echo "Description: ${{ github.event.pull_request.body }}"
          echo "Files changed: $(git diff --name-only origin/main...HEAD | wc -l)"
          echo ""
          
          # Simulate agent call
          echo "claude-code --agent pr-reviewer-gitops \\"
          echo "  --prompt 'Review PR: ${{ github.event.pull_request.title }}'"
          echo ""
          echo "Agent Response:"
          echo "==============="
          echo "CODE REVIEW FEEDBACK:"
          echo "Flask Task Manager implementation reviewed successfully."
          echo "✅ Proper error handling and validation"
          echo "✅ Clean code structure and organization" 
          echo "✅ Security considerations addressed"
          echo ""
          echo "VALIDATION STATUS:"
          echo "- Tests: ✅ Demo validation passed"
          echo "- Lint: ✅ Skipped for demo"
          echo "- CI Checks: ✅ Basic validation passed"
          echo ""
          echo "DECISION: ✅ MERGE: true"
          echo "PR Summary: Flask app meets all demo requirements and is ready for deployment"

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🤖 **PR Review Agent Analysis Complete**

            **CODE REVIEW FEEDBACK:**
            Flask Task Manager implementation reviewed successfully.
            ✅ Proper error handling and validation
            ✅ Clean code structure and organization  
            ✅ Security considerations addressed

            **VALIDATION STATUS:**
            - Tests: ✅ Demo validation passed  
            - CI Checks: ✅ Basic validation passed

            **DECISION: ✅ MERGE APPROVED**
            
            This PR meets all demo requirements and is ready for deployment.
            
            *Reviewed by pr-reviewer-gitops agent* 🤖`
            })